language: ruby
rvm:
  - 1.9.3
env:
  - DB=mysql
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
  - RAILS_ENV=test bundle exec teaspoon -q --coverage-reports=cobertura --format=tap
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - mysql -e 'create database projects_test'
services:
  - elasticsearch
